# Generated by Django 4.2.2 on 2023-07-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_gaim', models.CharField(max_length=100)),
                ('description_gaims', models.TextField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
