# Generated by Django 4.2.2 on 2023-07-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaim',
            name='img',
            field=models.ImageField(null=True, upload_to='image/%Y'),
        ),
    ]
