# Generated by Django 4.2.2 on 2023-07-30 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_likes_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentslike', to='main.gaim'),
        ),
    ]
